name: Periodic Apartment Scraper

permissions:
  contents: write  # Needed to push to gh-pages

on:
  schedule:
    # Run once per day at a random time (between 0:00 UTC and 23:59 UTC)
    - cron: "0 0 * * *"  # Placeholder for the cron job, we’ll handle randomness in the script
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    branches:
      - main

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessary for branch switching

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright dependencies
        run: |
          python -m playwright install

      - name: Run scraper with random delay
        run: |
          # Generate a random delay (between 0 and 86400 seconds = 24 hours)
          random_delay=$((RANDOM % 86400))
          echo "Random delay: $random_delay seconds"
          
          # Sleep for the random delay before scraping
          sleep $random_delay

          # Run the scraper script after the delay
          python scraper.py

      - name: Commit CSV to gh-pages
        run: |
          mkdir temp-gh-pages
          cp data/unit_prices.csv temp-gh-pages/
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git fetch origin gh-pages
          git checkout gh-pages || git checkout -b gh-pages
          
          cp temp-gh-pages/unit_prices.csv .
          git add unit_prices.csv
          git commit -m "Update unit prices" || echo "No changes to commit"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSV file (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: unit_prices
          path: data/unit_prices.csv
