name: Periodic Apartment Scraper

permissions:
  contents: write  # Needed to commit CSV updates

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright browser dependencies
        run: |
          python -m playwright install

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit updated CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/unit_prices.csv
          git diff --cached --quiet || git commit -m "Append new unit prices"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit_prices
          path: data/unit_prices.csv
