name: Periodic Apartment Scraper

on:
  schedule:
    - cron: "0 6,10,14,18,22 * * *"  # Runs at 6 AM, 10 AM, 2 PM, 6 PM, and 10 PM UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright dependencies
        run: |
          python -m playwright install

      - name: Run scraper
        run: |
          python scraper.py

      - name: Upload CSV file
        uses: actions/upload-artifact@v2
        with:
          name: unit_prices
          path: unit_prices.csv
